---
- name: Remove user
  hosts: all
  become: yes
  tasks:
    - name: Remove the user 'testuser'
      become: yes
      ansible.builtin.user:
        name: testuser
        state: absent
        remove: yes